#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# generate-keystore.sh
#
# Generates the release upload keystore for Idle Dozer and writes
# keystore.properties so Gradle can sign release builds automatically.
#
# Usage:
#   cd IdleDozer/
#   ./scripts/generate-keystore.sh
#
# Requirements: keytool (ships with every JDK installation)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

KEYSTORE_FILE="$ROOT_DIR/idledozer-release.jks"
PROPS_FILE="$ROOT_DIR/keystore.properties"

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║   Idle Dozer — Release Keystore Generator        ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ── Safety checks ─────────────────────────────────────────────────────────────
if [ -f "$KEYSTORE_FILE" ]; then
  echo "⚠️  A keystore already exists at: $KEYSTORE_FILE"
  read -rp "   Overwrite? (y/N): " OVERWRITE
  [[ "${OVERWRITE,,}" == "y" ]] || { echo "Aborted."; exit 0; }
fi

# ── Gather details ─────────────────────────────────────────────────────────────
echo "Fill in your developer details (used inside the keystore certificate)."
echo ""

read -rp "First and Last Name   : " CERT_NAME
read -rp "Organisational Unit   : " CERT_OU
read -rp "Organisation          : " CERT_O
read -rp "City / Locality       : " CERT_L
read -rp "State / Province      : " CERT_S
read -rp "Country Code (2-letter): " CERT_C

DNAME="CN=${CERT_NAME}, OU=${CERT_OU}, O=${CERT_O}, L=${CERT_L}, ST=${CERT_S}, C=${CERT_C}"

echo ""
read -rsp "Keystore password (min 6 chars): " STORE_PASS; echo ""
read -rsp "Confirm keystore password      : " STORE_PASS2; echo ""
[[ "$STORE_PASS" == "$STORE_PASS2" ]] || { echo "❌ Passwords do not match. Aborted."; exit 1; }
[[ ${#STORE_PASS} -ge 6 ]]            || { echo "❌ Password must be at least 6 characters. Aborted."; exit 1; }

KEY_ALIAS="idledozer"

# ── Generate keystore ──────────────────────────────────────────────────────────
echo ""
echo "⏳ Generating keystore…"
keytool -genkeypair \
  -keystore "$KEYSTORE_FILE" \
  -alias "$KEY_ALIAS" \
  -keyalg RSA \
  -keysize 2048 \
  -validity 10000 \
  -storepass "$STORE_PASS" \
  -keypass  "$STORE_PASS" \
  -dname    "$DNAME" \
  -storetype pkcs12

echo "✅ Keystore created: $KEYSTORE_FILE"

# ── Write keystore.properties ─────────────────────────────────────────────────
cat > "$PROPS_FILE" <<EOF
# Auto-generated by scripts/generate-keystore.sh — DO NOT COMMIT
storeFile=../idledozer-release.jks
storePassword=${STORE_PASS}
keyAlias=${KEY_ALIAS}
keyPassword=${STORE_PASS}
EOF

echo "✅ keystore.properties written: $PROPS_FILE"
echo ""
echo "🔒 IMPORTANT: Both files are in .gitignore — back them up somewhere safe."
echo "   If you lose the keystore you CANNOT update your app on the Play Store."
echo ""
echo "Next step: run  ./gradlew bundleRelease  from the IdleDozer/ directory."
